version: 2
jobs:
  build:
    working_directory: ~/MyTaxiUiAutomation
    docker:
    # Android the primary container
    - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
    - checkout
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies
    - save_cache:
        paths:
        - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
        name: Launch emulator
        command: emulator -avd test
        background: true
    - run:
        name: Wait emulator
        command: |
          # wait for it to have booted
          circle-android wait-for-boot
          # unlock the emulator screen
          sleep 30
    - run:
        name: Push app
        command: adb push /Users/dtadin/dtadin_portfolio/MyTaxiUiAutomation/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk /data/local/tmp/com.mytaxi.android_demo.test
    - run:
        name: Install app
        command: adb shell pm install -t -r "/data/local/tmp/com.mytaxi.android_demo.test"
    - run:
        name: Run EspressoTests
        command: adb shell am instrument -w -r   -e debug false -e class 'com.mytaxi.android_demo.SearchAndCallTest' com.mytaxi.android_demo.test/android.support.test.runner.AndroidJUnitRunner
    - store_artifacts:
        path: app/build/reports
        destination: reports
    - store_test_results:
        path: app/build/test-results